### ISSUE TITLE
Organization of yaml file

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/PhysicalConstantsDictionary#1]
I came across this new repository and wanted to pass along some initial thoughts:

I like the careful documentation of reference information here along with other metadata. However, I was curious about the choice of organizing this with the reference at the top level. I would find it more intuitive if the individual constants were at the top level, with sub-entries for different values from various references. In order to avoid massive duplication of the reference citation information, the references cited for each value would just be a string, which would essentially be a key into a separate table of reference citations.

i.e., something like this:

```
- name: newtonian_gravitation_constant
  units: m3 kg-1 s-2
  prec: double
  type: strict
  relative_uncertainty: 4.7E-05
  description: "
    Empirical constant used to calculate the attractive force between
    two bodies according to Newton's law of universal gravitation.
  "
  values:
    - value: 6.6740831E-11
      source: CODATA2014
    - value: 6.6740833E-11
      source: BILLMADEITUP2018
```

where there is a companion table giving citation information for CODATA2014 and BILLMADEITUP2018.

(It's possible that relative_uncertainty should also be listed separately for each source.)
